[libIIO]
arch = "x86_64"
git-tree-sha1 ="41b4cd1c039ffff3407ed5ce501b428c6ff5f93e"

    [[libIIO.download]]
    url = "https://github.com/JuliaTelecom/Artifact_libIIO/releases/download/v0.1/libIIO.tar.gz" 
    sha256 ="9fb217e438ab27fc81617ed1e03de8fd61bd50f39feb4c69e20e46e79025f7f0"
